---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Domain-ExpireDate
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: '2'
  Net::Whois::Raw: '1'
  Time::Piece: '0'
resources:
  repository: https://github.com/regru/Net-Domain-ExpireDate.git
version: '1.15'
