---
name: Net-Domain-ExpireDate
version: 0.94
author:
  - 'Walery Studennikov, <despair@cpan.org>'
abstract: 'Net::Domain::ExpireDate -- obtain expiration date of domain names'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::Whois::Raw: 1
  Time::Piece: 0
provides:
  Net::Domain::ExpireDate:
    file: lib/Net/Domain/ExpireDate.pm
    version: 0.94
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
