--- #YAML:1.0
name:                Net-Domain-ExpireDate
version:             0.90
abstract:            ~
license:             ~
author:              
    - Walery Studennikov <despair@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Getopt::Long:                  1
    Net::Whois::Raw:               1.3
    Test::More:                    0.5
    Time::Piece:                   1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
